WIP: Add option to use concaveman for extracting mission polygons
open-forest-observatory/ofo-r pull request #41
Opened 2024-12-06 23:24 UTC by russelldj

This adds the concave hull method implemented in `concaveman` as an alternative default method to compute the flight polygons. Currently it uses buffering and erosion. This seems to high-quality results that match the intuition for what a reasonable boundary is. I changed the concavity parameter from the default of 2 to 4 to encourage slightly more simplified shapes. 

![plot](https://github.com/user-attachments/assets/1a5fe0a7-30a4-4281-8366-887fa51c213c)

I still need to test this function before it's ready to merge.

2024-12-12 18:06 UTC, youngdjn requested changes
Concaveman as implemented here appears to be working great for missions with contiguous points. I agree the `concavity` value of `4` appears to work well. Unfortunately though, concaveman does not appear to deal well with cases of non-contiguous points. We need to tolerate this possibility because during initial image curation, it is possible we will encounter (non-ideal) datasets that have multiple non-contiguous groups of points. Here is how it dealt with one situation:

![image](https://github.com/user-attachments/assets/387fa390-6bbd-4a4a-a2cc-a5ea08df94b7)

You can reproduce this with the following script:

```R
devtools::load_all()
library(tidyverse)
library(sf)

exif = read_csv("/ofo-share/drone-imagery-organization/3b_exif-unprocessed/exif_2019-focal.csv")

ids = unique(exif$mission_id)

exif_foc = exif |>
  filter(mission_id == ids[1]) |>
  prep_exif()

exif_foc = exif_foc[c(1:100, 1001:1100), ]

poly = extract_mission_polygon(exif_foc)

plot(exif_foc |> st_as_sfc())
plot(poly, add = TRUE, lwd = 4)
```
Do you have any ideas on how to deal with this cleanly?

The concaveman method can also end up with a lot of legitimate border images falling outside of the generated polygon -- far more than the dilate-erode method. These would get dropped by the `crop_to_contiguous` step (which is enabled by default) in `extract_imagery_dataset_metadata` which we don't want. One way around this is to figure out how far beyond the generated boundary a legitimate image might fall, and adjust the buffer in [this line](https://github.com/open-forest-observatory/ofo-r/blob/0ccd0a45ded201d68b88e4d1fa34b8a08e9470fe/R/metadata-extraction_imagery_dataset.R#L517) to use that distance.

2024-12-12 18:06 UTC, youngdjn commented on R/metadata-extraction_imagery_dataset.R
> +library(concaveman)
Rather than adding dependencies to a function definitions file, they should be added to the `Imports` list in the `DESCRIPTION` file.

2024-12-12 18:06 UTC, youngdjn commented on R/metadata-extraction_imagery_dataset.R
> +    # This line is dangerous for single lines of images since
Could you finish this comment?

2024-12-13 14:17 UTC, russelldj commented on R/metadata-extraction_imagery_dataset.R
> +library(concaveman)
Thanks, I was confused why there weren't any other imports.

2024-12-13 14:21 UTC, russelldj commented
Thanks for doing these tests, I only checked a couple of the real datasets so I completely missed these issues. I can mess around with some of the parameters to see if I can get better results, but I am surprised it did so poorly with two widely-separated clusters of points. Maybe the concavity needs to be set lower.

I'm not quick sure why points are falling outside of the polygon. My guess would be this is because of the simplification step called later. We could always buffer out the concave hull before simplification to ensure that anything within the original polygon is still contained within the simplified version.

2025-02-18 15:10 UTC, russelldj commented
closing because this functionality was added in #57.

2025-02-18 15:10 UTC, closed without merging